# Generated by Django 5.1.7 on 2025-04-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_watchsession_watchsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchsession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
